# Generated by Django 3.1.3 on 2021-04-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210426_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='result',
            field=models.TextField(blank=True, default="Didn't discovered!", null=True, verbose_name='Result is:'),
        ),
    ]
